name = "DuBoisPlots"
uuid = "168d2eb6-d3a6-4344-96a8-585c4d8fe67b"
authors = ["Eirik Eylands Brandsaas <eirik.e.brandsaas@frb.gov> and contributors"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[compat]
DataFrames = "1"
CairoMakie = "0.8"
Weave = "0.10"
CSV = "0.10"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
